version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    assignees: [KiwiKilian]

  - package-ecosystem: github-actions
    directories: [/, '.github/workflows/**']
    schedule:
      interval: weekly
    assignees: [KiwiKilian]
