name: Run Tests
on:
  push:
    branches: [main, alpha]
  pull_request:
    branches: [main, alpha]
  merge_group:
    branches: [main, alpha]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # 4.4.0
        with:
          node-version: "24"
      - run: npm ci
      - run: npm test
