name: Run Tests
on:
  push:
    branches: [main, alpha]
  pull_request:
    branches: [main, alpha]
  merge_group:
    branches: [main, alpha]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # 4.4.0
        with:
          node-version: "22"
      - run: npm ci
      - run: npm test
